try{

    throw Error("Errore generico")

}catch(err){
    console.log(err)
}